library(lubridate)
DATASET<-read.csv('./dataset/DATASET.CSV')
plotanydata<-function(dataframe){
    dataframe$DATE=format(as.POSIXct(dataframe$DATE,format="%d/%m/%Y %H:%M"))
    dataframe$date=as.Date(dataframe$DATE)
    dataframe$time=format(as.POSIXct(dataframe$DATE),format="%H:%M")
    h <- seconds(hm(dataframe$time))
    plot(h, dataframe$Humidity,type = "l",lwd = 2, col = "red", xlab = "Tiempo (segundos)", ylab = "Temperatura")
    plot(h,dataframe$Temperature, type = "l",lwd = 2, col = "blue", xlab = "Tiempo (segundos)", ylab = "Temperatura")
}
lookingForAnomalies<-function(dataframe){
  print("The maximum value from temperature and humidity are: ")
  print("Temperature")
  print(max(dataframe$Humidity))
  print("Humidity")
  print(max(dataframe$Temperature))
  print("The minimum value from temperature and humidity are: ")
  print("Temperature")
  print(min(dataframe$Humidity))
  print("Humidity")
  print(min(dataframe$Temperature))
  print("Existen nans en la temperatura")
  print(dataframe$Temperature[is.nan(dataframe$Temperature)])
  print("Existen nans en la humedad")
  print(dataframe$Humidity[is.nan(dataframe$Humidity)])
}
plotanydata(DATASET)
lookingForAnomalies(DATASET)
